services:
  - type: web
    name: flask-app-sale-dashboard
    plan: starter
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    runtime:
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
